### ISSUE TITLE
VERSION file issue on case insensitive filesystems

### ISSUE THREAD

**Issue by cblecker** [genuinetools/sshb0t#2]
On case insensitive filesystems (like a default HFS+ or APFS drive on Darwin), the `version/` dir and the `VERSION` file conflict with each other. I know it's a nit-picky problem, but is it possible to rename one of them?

**Comment by jessfraz** [comment]
I changed this in a different way for all my repos, sorry, thanks!

**Comment by cblecker** [comment]
Thank you!
